Repository AlexTelon/FlexiCharge-Cross-Platform, pull requests merged in 2023-10, with the labels that each got.

#272 Update Notes - Sprint Planning & Retrospective.md
  documentation/internal-team-documentation/Notes - Sprint Planning & Retrospective.md
Labels: documentation

#270 Test/#259 investigate test charging
  android/build.gradle
  lib/app/app.locator.dart
  lib/app/app.router.dart
  lib/ui/screens/qr_scanner/qr_scanner_view.dart
  lib/ui/screens/qr_scanner/qr_scanner_viewmodel.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, documentation, enhancement, quality, test

#279 Update Notes - Sprint Planning & Retrospective.md
  documentation/internal-team-documentation/Notes - Sprint Planning & Retrospective.md
Labels: documentation

#283 Feature/#53 show live charging metrics from backend
  ios/Podfile.lock
  lib/models/charger_point.dart
  lib/models/transaction.dart
  lib/services/charger_api_service.dart
  lib/services/transaction_api_service.dart
  lib/services/user_api_service.dart
  lib/ui/sheets/map_bottom_sheet/select_charger.dart
  lib/ui/sheets/map_bottom_sheet/snappingcheet_viewmodel.dart
  lib/ui/sheets/top_sheet/top_sheet_view.dart
  lib/ui/sheets/top_sheet/top_sheet_view_model.dart
  lib/ui/widgets/charging_in_progress.dart
  lib/ui/widgets/stop_chargning_button.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation

#292 Added documentation on how to start the app
  README.md
  documentation/Documentation FlexiCharge-Cross-Platform.docx
  documentation/Documentation FlexiCharge-Cross-Platform.pdf
Labels: documentation

#295 Feature/#288 adapt code to backend incoming changes
  lib/models/charger.dart
  lib/models/charger_point.dart
  lib/models/old_transaction.dart
  lib/services/charger_api_service.dart
  lib/services/local_data.dart
  lib/services/transaction_api_service.dart
  lib/ui/screens/home_page/home_viewmodel.dart
  lib/ui/sheets/map_bottom_sheet/select_charger.dart
  lib/ui/sheets/map_bottom_sheet/snappingcheet_viewmodel.dart
  lib/ui/sheets/top_sheet/top_sheet_view.dart
  lib/ui/sheets/top_sheet/top_sheet_view_model.dart
Labels: enhancement

#297 Implemented new transaction functionality
  lib/models/transaction.dart
  lib/services/local_data.dart
  lib/services/transaction_api_service.dart
  lib/ui/screens/home_page/home_viewmodel.dart
  lib/ui/sheets/map_bottom_sheet/snappingcheet_viewmodel.dart
  lib/ui/sheets/top_sheet/top_sheet_view.dart
  lib/ui/sheets/top_sheet/top_sheet_view_model.dart
  pubspec.lock
Labels: enhancement
